source /usr/share/defaults/etc/profile

# Moje aliasy
alias eoit="sudo eopkg it"
alias eosr="eopkg sr"
alias eoup="sudo eopkg up"

alias ssh-nc="ssh cerdivall@46.101.188.117"
alias ssh-dell="ssh 'cerdivall@192.168.100.107'"

powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/lib64/python2.7/site-packages/powerline/bindings/bash/powerline.sh

neofetch
